// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reparaciones.Infrastructure.Context;

#nullable disable

namespace Reparaciones.Infrastructure.Migrations
{
    [DbContext(typeof(ReparacionesContext))]
    [Migration("20260424030907_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reparaciones.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Reparaciones.Domain.Entities.Electrodomestico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Electrodomesticos");
                });

            modelBuilder.Entity("Reparaciones.Domain.Entities.Garantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReparacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReparacionId")
                        .IsUnique();

                    b.ToTable("Garantias");
                });

            modelBuilder.Entity("Reparaciones.Domain.Entities.Reparacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoManoObra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ElectrodomesticoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ElectrodomesticoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("Reparaciones");
                });

            modelBuilder.Entity("Reparaciones.Domain.Entities.ReparacionRepuesto", b =>
                {
                    b.Property<int>("ReparacionId")
                        .HasColumnType("int");

                    b.Property<int>("RepuestoId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.HasKey("ReparacionId", "RepuestoId");

                    b.HasIndex("RepuestoId");

                    b.ToTable("ReparacionRepuestos");
                });

            modelBuilder.Entity("Reparaciones.Domain.Entities.Repuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("Reparaciones.Domain.Entities.Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("Reparaciones.Domain.Entities.Garantia", b =>
                {
                    b.HasOne("Reparaciones.Domain.Entities.Reparacion", "Reparacion")
                        .WithOne("Garantia")
                        .HasForeignKey("Reparaciones.Domain.Entities.Garantia", "ReparacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reparacion");
                });

            modelBuilder.Entity("Reparaciones.Domain.Entities.Reparacion", b =>
                {
                    b.HasOne("Reparaciones.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Reparaciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reparaciones.Domain.Entities.Electrodomestico", "Electrodomestico")
                        .WithMany("Reparaciones")
                        .HasForeignKey("ElectrodomesticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reparaciones.Domain.Entities.Tecnico", "Tecnico")
                        .WithMany("Reparaciones")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Electrodomestico");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("Reparaciones.Domain.Entities.ReparacionRepuesto", b =>
                {
                    b.HasOne("Reparaciones.Domain.Entities.Reparacion", "Reparacion")
                        .WithMany("ReparacionRepuestos")
                        .HasForeignKey("ReparacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reparaciones.Domain.Entities.Repuesto", "Repuesto")
                        .WithMany("ReparacionRepuestos")
                        .HasForeignKey("RepuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reparacion");

                    b.Navigation("Repuesto");
                });

            modelBuilder.Entity("Reparaciones.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Reparaciones");
                });

            modelBuilder.Entity("Reparaciones.Domain.Entities.Electrodomestico", b =>
                {
                    b.Navigation("Reparaciones");
                });

            modelBuilder.Entity("Reparaciones.Domain.Entities.Reparacion", b =>
                {
                    b.Navigation("Garantia");

                    b.Navigation("ReparacionRepuestos");
                });

            modelBuilder.Entity("Reparaciones.Domain.Entities.Repuesto", b =>
                {
                    b.Navigation("ReparacionRepuestos");
                });

            modelBuilder.Entity("Reparaciones.Domain.Entities.Tecnico", b =>
                {
                    b.Navigation("Reparaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
